#!/bin/bash

get_all_mark() {
    ids=$(swaymsg -t get_tree | jq -r '.. | select(.marks[]? | match("^'$1'\\s.*"))?.id')
    printf "$ids"
}
set_all_mark() {
    ids=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).floating_nodes[].id')
    for id in $ids;do
	swaymsg [con_id="$id"] mark "$1 $id", floating enable
	swaymsg [con_id="$id"] move container scratchpad
    done
}
# focus based on group number, used by select
if [[ $1 = "select" ]];then
    for id in $(get_all_mark $2);do
	swaymsg [con_id="$id"] scratchpad show
	swaymsg focus child
    done
fi

if [[ $1 = "move" ]];then
    # get only particular focused window
    if [[ -n $3 ]];then
	focused=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).floating_nodes[] | recurse(.nodes[]) as $parent | select($parent.focused==true).id')
	if [[ -z $focused ]];then
	    exit
	fi
	swaymsg [con_id="$focused"] mark "$2 $focused", floating enable
	swaymsg [con_mark="^$2\s.*"] move container scratchpad
    else
	# move all floating windows to group
	set_all_mark $2
    fi
fi

swaymsg mode "default"
