#!/bin/bash

get_container() {
    container="$(swaymsg -t get_tree | jq -r '.. | select(.nodes? and .name==null) | recurse(.nodes[]) as $parent | select($parent.focused).id')"
    printf $container
}

if [[ $1 == "parent" ]];then
    swaymsg focus parent
    sway-overfocus group-rw group-dw
    swaymsg focus child
    exit
fi

if [[ $1 == "container" ]];then
    container=$(get_container)
    swaymsg [con_id=$container] focus
    exit
fi

if [[ $1 == "set_pin" ]];then
    swaymsg [con_id=__focused__] mark "pinned"
    exit
fi

if [[ $1 == "focus_pin" ]];then
    swaymsg [con_mark="pinned"] focus
    exit
fi

if [[ $1 == "split_move" ]];then
    split_move=$(get_container | tail -n1)
    swaymsg [con_id=$split_move] mark "split_move"
    swaymsg [con_mark="pinned"] move container mark "split_move", unmark "split_move", unmark "pinned"
#    swaymsg unmark "pinned"
#    swaymsg unmark "split_move"
#    swaymsg [con_mark="pinned"] move container to mark "split_move"
    exit
fi
