#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 "1 $RANDOM" "2 $RANDOM" "3 $RANDOM" "4 $RANDOM"

bspc config border_width         0
bspc config window_gap           0
bspc config focused_border_color "#DC143C"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle 	 true
bspc config presel_feedback_color "#6F0000"

bspc rule -a st-256color:st-256color:ranger state=floating rectangle=1200x500+0+0 center=on
bspc rule -a st-256color:st-256color:stfloat state=floating center=on
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=floating
bspc rule -a okular state=floating rectangle=900x700 center=on
bspc rule -a dolphin state=floating
bspc rule -a st-256color:st-256color:htop desktop=^1
bspc rule -a Pavucontrol state=floating
bspc rule -a Nvidia-settings state=floating

st htop -t htop &
setxkbmap -layout us,ru,br -option grp:shifts_toggle

feh --bg-fill /home/perplex/images/cover.png 

xsetroot -cursor_name left_ptr
unclutter -idle 5 -jitter 20 -root &
/home/perplex/dotfiles/bspwm/nodes-daemon.sh &
/home/perplex/dotfiles/bspwm/node-focus-daemon.sh &

